### ISSUE TITLE
off-topic

### ISSUE THREAD

**Issue by bucanero** [DarkNacho/TrophyWizard#2]
hello @DarkNacho 

off-topic question, by any chance are you one of the admins at the Bruteforce savedata forum? ( https://bruteforcesavedata.forumms.net/ )

I ask because I've been trying to sign up, I created my account a couple of times but I get an email that says `the administrator of the board will need to activate it before you can log in.`, and I'm always stuck at that point.

If you're an admin, could you help me out? I'd like to check some information from the forum to improve my PS3 apps
thanks!

**Comment by DarkNacho** [comment]
> hello @DarkNacho
> 
> off-topic question, by any chance are you one of the admins at the Bruteforce savedata forum? ( https://bruteforcesavedata.forumms.net/ )
> 
> I ask because I've been trying to sign up, I created my account a couple of times but I get an email that says `the administrator of the board will need to activate it before you can log in.`, and I'm always stuck at that point.
> 
> If you're an admin, could you help me out? I'd like to check some information from the forum to improve my PS3 apps
> thanks!

Sorry for the late reply, I am admin by rank but without acces to the administration board, I can help you with if I can.
Discord: Dark Nacho#6723
Mail: dark_nacho_xd@hotmail.cl

**Comment by bucanero** [comment]
hola, gracias por la respuesta, por suerte lo del foro ya lo he solucionado, me han activado la cuenta

una pregunta, entiendo eres el autor del "Resident Evil Zero save editor" para los save-games de PS3, verdad?
estuve agregando las encriptaciones custom a la aplicacion Apollo, y me gustaria agregar la del Resident Evil 0 tambien.

Entiendo que el savegame está usando el metodo Blowfish (como el resident evil HD remaster y revelations 2). 
Si no te molesta, podrias pasarme la key de encriptacion que usa el RE Zero? con la key seria suficiente para que Apollo pueda desencriptar tambien los archivos de RE Zero.

gracias, saludos!

**Comment by DarkNacho** [comment]
> hola, gracias por la respuesta, por suerte lo del foro ya lo he solucionado, me han activado la cuenta
> 
> una pregunta, entiendo eres el autor del "Resident Evil Zero save editor" para los save-games de PS3, verdad?
> estuve agregando las encriptaciones custom a la aplicacion Apollo, y me gustaria agregar la del Resident Evil 0 tambien.
> 
> Entiendo que el savegame está usando el metodo Blowfish (como el resident evil HD remaster y revelations 2).
> Si no te molesta, podrias pasarme la key de encriptacion que usa el RE Zero? con la key seria suficiente para que Apollo pueda desencriptar tambien los archivos de RE Zero.
> 
> gracias, saludos!

Agregue un gist con información relevante de la mayoría de los [resident evil](https://gist.github.com/DarkNacho/172af58c814e8d77e04fff8bc3357dc7), por ahora no encontré resident evil 0 pero cuando lo encuentre lo actualizaré y avisaré

**Comment by bucanero** [comment]
> 
> Agregue un gist con información relevante de la mayoría de los [resident evil](https://gist.github.com/DarkNacho/172af58c814e8d77e04fff8bc3357dc7), por ahora no encontré resident evil 0 pero cuando lo encuentre lo actualizaré y avisaré

gracias, al final el RE Zero tiene la misma key que el HD remaster, lo he verificado. 
Por cierto, de la lista que enviaste, entiendo que el RE 2 y el RE 7 son solo para PS4, no hay version para ps3 de esos juegos.
